[window]
decorations = "none"
startup_mode = "maximized"
dynamic_padding = true
decorations_theme_variant = "Dark"
opacity = 1

[window.dimensions]
#columns = 10
#lines = 10

[window.padding]
x = 6
y = 0

[cursor]
style = "Beam"

[mouse]
hide_when_typing = false

[scrolling]
history = 1000
multiplier = 10

[font]
size = 12

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0


[font.normal]
family = "MesloLGLDZ Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGLDZ Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGLDZ Nerd Font"
style = "Italic"

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
